Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\hp\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data = np.array([[1, 2], [3, 4], [5, 6] ])
type(data)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-1467f4f2f8ca>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mdata[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[1;33m[[0m[1;33m[[0m[1;36m1[0m[1;33m,[0m [1;36m2[0m[1;33m][0m[1;33m,[0m [1;33m[[0m[1;36m3[0m[1;33m,[0m [1;36m4[0m[1;33m][0m[1;33m,[0m [1;33m[[0m[1;36m5[0m[1;33m,[0m [1;36m6[0m[1;33m][0m [1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mtype[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

